# version: '3.9'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: django_app
    command: >
      sh -c "/app/docker-entrypoint.sh &&
             daphne -b 0.0.0.0 -p 8000 backend.asgi:application"
    volumes:
      - ./backend:/app
      - static_volume:/app/static
      - media_volume:/app/media
    env_file:
      - ./backend/.env
    environment:
      - DJANGO_SETTINGS_MODULE=backend.settings
      - DATABASE_HOST=host.docker.internal
      - APP_ENV=local
    ports:
      - "127.0.0.1:8000:8000"
    networks:
      - app-network
    depends_on:
      - redis

  redis:
    image: redis:7
    container_name: redis_cache
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: development
    container_name: react_frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - APP_ENV=local
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    ports:
      - "127.0.0.1:3000:3000"
    stdin_open: true
    tty: true
    depends_on:
      - backend
    networks:
      - app-network

  # Production nginx service (commented out for development)
  # nginx:
  #   image: nginx:1.25-alpine
  #   container_name: production_web
  #   volumes:
  #     - static_volume:/usr/share/nginx/html/static
  #     - media_volume:/usr/share/nginx/html/media
  #     - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - backend
  #     - frontend
  #   networks:
  #     - app-network

  celery_worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: celery_worker
    command: celery -A backend worker --loglevel=info
    volumes:
      - ./backend:/app
      - media_volume:/app/media
      - static_volume:/app/static
    env_file:
      - ./backend/.env
    environment:
      - DJANGO_SETTINGS_MODULE=backend.settings
      - DATABASE_HOST=host.docker.internal
    depends_on:
      - backend
      - redis
    networks:
      - app-network

  celery_beat:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: celery_beat
    command: celery -A backend beat --loglevel=info
    volumes:
      - ./backend:/app
      - media_volume:/app/media
      - static_volume:/app/static
    env_file:
      - ./backend/.env
    environment:
      - DJANGO_SETTINGS_MODULE=backend.settings
      - DATABASE_HOST=host.docker.internal
    depends_on:
      - backend
      - redis
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  redis_data:
    driver: local
  static_volume:
    driver: local
  media_volume:
    driver: local