"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/
import os

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
from datetime import timedelta
from celery.schedules import crontab
import ssl

import logging

from urllib.parse import urlparse
from .redis_connection import CustomSSLConnection, get_custom_ssl_context
# NOTE: loading of .env is done after BASE_DIR is known so the file can be
# referenced reliably regardless of CWD.

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from the .env file in the project root when
# present. This ensures values in .env are available even when the process's
# current working directory differs (e.g. docker, systemd, or other runners).
env_path = BASE_DIR / '.env'
if env_path.exists():
    load_dotenv(dotenv_path=env_path)


# Helper to fetch env vars and treat empty/whitespace-only values as missing
# (so an empty key in .env won't override a real system env value).
def env(key, default=None):
    v = os.getenv(key)
    if v is None:
        return default
    v = v.strip()
    return v if v != '' else default

# Parse redis url (use a safe default if not provided)
redis_url = env("CHANNELS_URLS")
parsed_url = urlparse(redis_url or 'redis://localhost:6379/0')

ssl_context = get_custom_ssl_context()


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['*']

# Application definition
INSTALLED_APPS = [
    'corsheaders',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.sites',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'channels',
    # 'django_prometheus',
    'drf_spectacular',
    'geographies',
    'users',
    'rest_framework',
    'pendingusers',
    'notifications',
    'event',
    'reports',
    'activity_reports',
    'chat',
    'blog',
    'blog_related',


]


MIDDLEWARE = [
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django_prometheus.middleware.PrometheusBeforeMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_prometheus.middleware.PrometheusAfterMiddleware',
]

STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
    'NAME':  env('DATABASE_NAME'),
    'USER': env('DATABASE_USER'),
    'PASSWORD': env('DATABASE_PASSWORD'),
    'HOST': env('DATABASE_HOST'),
    'PORT': env('DATABASE_PORT'),
        'OPTIONS': {
            'options': '-c search_path=public,geographies'
        }
    }
}

WSGI_APPLICATION = 'backend.wsgi.application'

ASGI_APPLICATION = 'backend.asgi.application'
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'users.authentication.CookieJWTAuthentication',  # Custom cookie auth
        'rest_framework_simplejwt.authentication.JWTAuthentication',  # Fallback to header
    ),
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
    )
}




SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=5),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': '123445789',
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    # New cookie settings for JWT in cookies:
    'AUTH_COOKIE': 'access_token',                  # Name of the cookie where JWT is stored
    'AUTH_COOKIE_SECURE': False,                     # Use True if HTTPS
    'AUTH_COOKIE_HTTP_ONLY': True,                   # Recommended for security
    'AUTH_COOKIE_PATH': '/',                          # Path scope of the cookie
    'AUTH_COOKIE_SAMESITE': 'Lax',                    # Depends on your frontend/backend setup
    # 'AUTH_COOKIE_DOMAIN': 'localhost',                # Add this line
}


# CHANNEL_LAYERS = {
#     "default": {
#         "BACKEND": "channels_redis.core.RedisChannelLayer",
#         "CONFIG": {
#             "hosts": [(os.environ.get("CHANNELS_URLS" ))],  # Use 'redis' as the hostname
#         },
#     },
# }



CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [{
                "host": parsed_url.hostname,
                "port": parsed_url.port,
                "username": parsed_url.username,
                "password": parsed_url.password,
                "db": int(parsed_url.path.lstrip("/")) if parsed_url.path else 0,
                "connection_class": CustomSSLConnection,
                "ssl_context": ssl_context,
            }],
            "symmetric_encryption_keys": [env("SECRET_KEY")],
        },
    },
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL = 'users.Petitioner'  # Use the custom user model


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'
CELERY_TIMEZONE = 'Asia/Kolkata'
CELERY_ENABLE_UTC = False


USE_I18N = True

USE_TZ = True

SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SAMESITE = "None"
CSRF_COOKIE_SAMESITE = "None"
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATIC_URL = 'static/'

MEDIA_URL = '/media/'  # URL path for media files
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CORS_ALLOWED_ORIGINS = [env('Frontendurl'),  "https://45e8-2405-201-c057-c039-b159-12fc-9adc-48c0.ngrok-free.app","https://pfs-ui-f7bnfbg9agb4cwcu.canadacentral-01.azurewebsites.net", "http://127.0.0.1:3000","http://localhost:3000"]

CORS_ALLOW_CREDENTIALS = True

CSRF_TRUSTED_ORIGINS = [env('Frontendurl'), "https://45e8-2405-201-c057-c039-b159-12fc-9adc-48c0.ngrok-free.app","https://pfs-ui-f7bnfbg9agb4cwcu.canadacentral-01.azurewebsites.net","http://127.0.0.1:3000","http://localhost:3000"]

CSRF_COOKIE_NAME = "csrftoken"
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,

    'formatters': {
        'verbose': {
            # Added :{lineno} to include line number in every log
            'format': '{levelname} {asctime} {module} {filename}:{lineno} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },

    'handlers': {
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'console_unfiltered': {  # New handler without debug filter
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },

    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
        'django.server': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'backend': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        # Add these new loggers
        'activity_reports': {
            'handlers': ['console_unfiltered'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'activity_reports.consumers': {
            'handlers': ['console_unfiltered'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'celery': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
          'users': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'users.tasks': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'users.models': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },

    # Root logger - safety net
    'root': {
        'handlers': ['console_unfiltered'],
        'level': 'WARNING',
    }
}


# REST Framework settings

REST_FRAMEWORK = {

    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    )
}

CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL' )
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND' )
CELERY_TIMEZONE = 'Asia/Kolkata'
CELERY_BEAT_SCHEDULE = {
    # 'simulate-user-growth': {
    #     'task': 'users.tasks.add_live_users',
    #     'schedule':300.0,
    # },

    
    'generate-daily-report': {
        'task': 'reports.tasks.generate_daily_report',
        'schedule': crontab(minute=20, hour=0),  # Midnight every day
        'options': {
            'expires': 60 * 60 * 2,  # Expire after 2 hours
        }
    },
    'simulate-activity-every-3-minutes': {
        'task': 'activity_reports.tasks.simulate_realtime_activity',
        'schedule': crontab(minute='*/10'),  # Every 3 minutes
        'options': {
            'expires': 120,  # Expire after 2 minutes if not run
        }
    },
     'generate-monthly-report': {
        'task': 'reports.tasks.generate_monthly_report',
        'schedule': crontab(minute=0, hour=2, day_of_month=1),  # 2:00 AM on the 1st of each month
        'options': {
            'expires': 60 * 60 * 4,  # Expire after 4 hours
        }
    },
    'generate-overall-report': {
        'task': 'reports.tasks.generate_overall_report',
        'schedule': crontab(minute=30, hour=1),  # 1:30 AM every day
        'options': {
            'expires': 60 * 60 * 3,  # Expire after 3 hours
        }
    },
    # 'populate-milestones-sequence': {
    #     'task': 'users.tasks.populate_milestones_sequence',
    #     'schedule': crontab(minute='*/10'),  # Every 180 seconds (3 minutes)
    #     'options': {
    #         'expires': 120,  # Expire after 2 minutes if not run
    #     }
    # },

       'generate-daily-activity-report': {
        'task': 'activity_reports.tasks.generate_daily_activity_report',
        'schedule': crontab(minute=30, hour=1),  # 1:30 AM every day
        'options': {
            'expires': 60 * 60 * 3,
        }
    },
    'generate-weekly-activity-report': {
        'task': 'activity_reports.tasks.generate_weekly_activity_report',
        'schedule': crontab(minute=0, hour=2, day_of_week=1),  # 2:00 AM every Monday
        'options': {
            'expires': 60 * 60 * 4,
        }
    },
    'generate-monthly-activity-report': {
        'task': 'activity_reports.tasks.generate_monthly_activity_report',
        'schedule': crontab(minute=0, hour=3, day_of_month=1),  # 3:00 AM on the 1st of each month
        'options': {
            'expires': 60 * 60 * 6,
        }
    },

}

